# Generated by Django 3.2.4 on 2021-06-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile2departemen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bod',
            field=models.BooleanField(default=False),
        ),
    ]
