# Generated by Django 3.2.4 on 2021-06-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_bod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bod',
            field=models.CharField(choices=[('Y', 'BOD'), ('N', 'Non BOD')], max_length=1, verbose_name='Status BOD ?'),
        ),
    ]
