# Generated by Django 3.2.4 on 2021-06-11 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Masukkan company code', max_length=5, null=True, verbose_name='Company Code')),
                ('name', models.CharField(blank=True, help_text='Masukkan nama company', max_length=50, null=True, verbose_name='Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Please fill name of the departmen', max_length=50, null=True, verbose_name='Name of Departemen')),
                ('location', models.CharField(blank=True, help_text='Please fill name of location', max_length=50, null=True, verbose_name='Location')),
                ('description', models.CharField(blank=True, help_text='Please fill the description', max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Please fill meeting name', max_length=100, null=True, verbose_name='Meeting Name')),
                ('meeting_date', models.DateField(blank=True, help_text='Please fill date of the meeting', null=True, verbose_name='Tanggal meeting')),
                ('start_time', models.TimeField(blank=True, help_text='Please fill start time of the meeting', null=True, verbose_name='Start time')),
                ('end_time', models.TimeField(blank=True, help_text='Please fill end time of the meeting', null=True, verbose_name='End time')),
                ('organizer', models.CharField(blank=True, help_text="Please fill organizer's name", max_length=50, null=True, verbose_name='Organizer')),
                ('notulen', models.CharField(blank=True, help_text="Please fill notulen's name", max_length=50, null=True, verbose_name='Notulen')),
                ('location', models.CharField(blank=True, help_text="Please fill the location's name", max_length=100, null=True, verbose_name='Location')),
                ('meeting2company', models.ForeignKey(help_text='Masukkan data company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pica.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Topik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_topik', models.CharField(blank=True, help_text="Please fill topic's name", max_length=200, null=True, verbose_name='Nama Topik')),
                ('problem_owner', models.CharField(blank=True, help_text="Please fill problem's owner", max_length=100, null=True, verbose_name='Problem Owner')),
                ('problem', models.TextField(blank=True, help_text='Please fill the problem', null=True, verbose_name='Problem')),
                ('solution', models.TextField(blank=True, help_text='Please fill the solution', null=True, verbose_name='Solution')),
                ('due_date', models.DateField(blank=True, help_text='Please fill the due date of the problem', null=True, verbose_name='Due date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN', max_length=5)),
                ('topik2departemen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departemen2topik', to='pica.departemen', verbose_name='Departemen')),
                ('topik2meeting', models.ManyToManyField(blank=True, related_name='meeting2topik', to='pica.Meeting')),
                ('topik2user', models.ForeignKey(blank=True, help_text='Please fill the person in charge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2topik', to=settings.AUTH_USER_MODEL, verbose_name='Person in charge')),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Masukkan nama peserta', max_length=50, null=True, verbose_name='Nama Peserta')),
                ('email', models.EmailField(blank=True, help_text='Masukkan email adddress', max_length=254, null=True, verbose_name='Email address')),
                ('bod', models.BooleanField(default=False, help_text='Apakah masuk dalam list BOD?', verbose_name='BOD')),
                ('peserta2company', models.ForeignKey(help_text='Pilih company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company2peserta', to='pica.company', verbose_name='Company')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting2peserta',
            field=models.ManyToManyField(related_name='peserta2meeting', to='pica.Peserta'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting2user',
            field=models.ManyToManyField(blank=True, related_name='user2meeting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activity', models.DateField(blank=True, help_text='Masukkan tanggal aktivitas', null=True, verbose_name='Date Activity')),
                ('keterangan', models.CharField(max_length=255)),
                ('activity2topik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pica.topik')),
                ('activity2user', models.ForeignKey(help_text='Masukkan PIC', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2activity', to=settings.AUTH_USER_MODEL, verbose_name='PIC')),
            ],
        ),
    ]
