# Generated by Django 3.2.4 on 2021-06-11 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departemen',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='departemen',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='departemen',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nama Departemen'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='nama_topik',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Topik'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='problem',
            field=models.TextField(blank=True, null=True, verbose_name='Problem'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='problem_owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Problem Owner'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='topik2user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2topik', to=settings.AUTH_USER_MODEL, verbose_name='Person in charge'),
        ),
    ]
