# Generated by Django 3.2.4 on 2021-06-15 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0002_auto_20210611_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nama Affco')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='topik',
            name='topik2affco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affco2topik', to='pica.affco'),
        ),
    ]
