# Generated by Django 3.2.4 on 2021-06-15 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pica', '0008_auto_20210615_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topik',
            name='topik2user',
            field=models.ManyToManyField(related_name='user2topik', to=settings.AUTH_USER_MODEL, verbose_name='Person in charge'),
        ),
    ]
