# Generated by Django 3.2.4 on 2021-06-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0010_auto_20210616_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('pic_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pic_departemen', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='topik',
            name='topik2user',
        ),
        migrations.AddField(
            model_name='topik',
            name='topik2pic',
            field=models.ManyToManyField(related_name='pic2topik', to='pica.PIC', verbose_name='Person in charge'),
        ),
    ]
