# Generated by Django 3.2.4 on 2021-06-16 06:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0011_auto_20210616_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topik',
            name='action',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='problem',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Problem'),
        ),
    ]
