# Generated by Django 3.2.4 on 2021-06-16 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0012_auto_20210616_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting2company',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting2peserta',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting2user',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='notulen',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='title',
        ),
        migrations.AddField(
            model_name='meeting',
            name='nama_forum',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='topik',
            name='issued_date',
            field=models.DateField(verbose_name='Issued Date'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('SUSPEND', 'SUSPEND'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=8),
        ),
        migrations.AlterField(
            model_name='topik',
            name='topik2departemen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departemen2topik', to='pica.departemen', verbose_name='Function/Divisi/Departemen'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='topik2meeting',
            field=models.ManyToManyField(blank=True, related_name='meeting2topik', to='pica.Meeting', verbose_name='Meeting Forum'),
        ),
    ]
