# Generated by Django 3.2.4 on 2021-06-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0014_alter_topik_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topik',
            name='issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Issued Date'),
        ),
    ]
