# Generated by Django 3.2.4 on 2021-06-18 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0015_alter_topik_issued_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_forum', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='nama_forum',
        ),
        migrations.RemoveField(
            model_name='topik',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='topik',
            name='topik2affco',
        ),
        migrations.RemoveField(
            model_name='topik',
            name='topik2pic',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting2peserta',
            field=models.ManyToManyField(related_name='peserta2meeting', to='pica.Peserta', verbose_name='Peserta meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='notulen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='peserta2departemen',
            field=models.ForeignKey(blank=True, help_text='Pilih Departemen', null=True, on_delete=django.db.models.deletion.CASCADE, to='pica.departemen', verbose_name='Departemen'),
        ),
        migrations.AddField(
            model_name='topik',
            name='topik2company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company2topik', to='pica.company', verbose_name='Problem Owner'),
        ),
        migrations.AddField(
            model_name='topik',
            name='topik2peserta',
            field=models.ManyToManyField(related_name='peserta2topik', to='pica.Peserta', verbose_name='Person in Charge'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nama Company'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='nama_topik',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Topik'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('HOLD', 'HOLD'), ('PROGRESS', 'PROGRESS'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=8),
        ),
        migrations.AlterField(
            model_name='topik',
            name='topik2meeting',
            field=models.ManyToManyField(related_name='meeting2topik', to='pica.Meeting', verbose_name='Meeting'),
        ),
        migrations.DeleteModel(
            name='Affco',
        ),
        migrations.DeleteModel(
            name='PIC',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting2forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum2meeting', to='pica.forum', verbose_name='Forum'),
        ),
    ]
