# Generated by Django 3.2.4 on 2021-06-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0019_auto_20210620_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='group_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
