# Generated by Django 3.2.4 on 2021-06-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0020_peserta_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='company',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
