# Generated by Django 3.2.4 on 2021-06-21 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0021_forum_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='company',
        ),
    ]
