# Generated by Django 3.2.4 on 2021-06-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0023_topik_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topik',
            name='due_date',
            field=models.DateField(null=True, verbose_name='Due date'),
        ),
    ]
