# Generated by Django 3.2.4 on 2021-06-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0025_alter_activity_activity2topik'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='due_date',
            field=models.DateField(blank=True, help_text='Masukkan tanggal due date', null=True, verbose_name='Due Date'),
        ),
    ]
