# Generated by Django 3.2.4 on 2021-07-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0027_auto_20210627_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='departemen',
            name='location',
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='nama_topik',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Topik'),
        ),
    ]
