# Generated by Django 3.2.4 on 2021-07-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0028_auto_20210702_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
