# Generated by Django 3.2.4 on 2021-07-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0029_activity_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='topik',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
