# Generated by Django 3.2.4 on 2021-07-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0030_topik_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topik',
            name='topik2meeting',
        ),
        migrations.AddField(
            model_name='topik',
            name='topik2meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting2topik', to='pica.meeting', verbose_name='Meeting'),
        ),
    ]
