# Generated by Django 3.2.4 on 2021-07-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0031_auto_20210707_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='topik',
            name='group_code',
        ),
        migrations.AddField(
            model_name='forum',
            name='forum2company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company2forum', to='pica.company'),
        ),
    ]
