# Generated by Django 3.2.4 on 2021-07-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0032_auto_20210707_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topik',
            name='topik2meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting2topik', to='pica.meeting', verbose_name='Meeting'),
        ),
    ]
