# Generated by Django 3.2.4 on 2021-07-07 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pica', '0033_alter_topik_topik2meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity2user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2activity', to=settings.AUTH_USER_MODEL, verbose_name='PIC'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
