# Generated by Django 3.2.4 on 2021-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0034_auto_20210707_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
