# Generated by Django 3.2.4 on 2021-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0035_alter_activity_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('HOLD', 'HOLD'), ('PROGRESS', 'PROGRESS'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=8),
        ),
    ]
