# Generated by Django 3.2.4 on 2021-07-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0036_auto_20210707_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='status',
            new_name='status_act',
        ),
    ]
