# Generated by Django 3.2.4 on 2021-07-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0038_remove_activity_status_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('HOLD', 'HOLD'), ('PROGRESS', 'PROGRESS'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=8),
        ),
    ]
